apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-deployment
  namespace: remediation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop
  template:
    metadata:
      labels:
        app: crash-loop
    spec:
      containers:
      - name: sample
        image: srinivas080801/book-service:latest
        ports:
        - containerPort: 8080
