apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter-job
  namespace: remediation
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter
        command:
          - "/bin/sh"
          - "-c"
          - >
            kube-hunt --pod 
      restartPolicy: Never
