apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-waiting-deployment
  namespace: remediation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-waiting
  template:
    metadata:
      labels:
        app: pod-waiting
    spec:
      containers:
      - name: nginx
        image: ngin
        ports:
        - containerPort: 8080
