spring.application.name=s3-policies

spring.main.allow-bean-definition-overriding=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.63.14.112:3306/mysql
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true


username=srinivas
password=srinivas@123
jenkinsurl=http://10.63.20.41:8080/
jenkinstoken=11b728d9a3614989f152e78fbe947b4519
