spring.main.allow-bean-definition-overriding=true
giturl=http://10.63.33.181:32471/
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.63.20.126:32001/register_cs
spring.jpa.hibernate.ddl-auto = create
spring.datasource.username=admin
spring.datasource.password=Admin@123

spring.jpa.show-sql=true
