apiVersion: apps/v1
kind: Deployment
metadata:
  name: kor-application
  namespace: ar
  labels:
    app: kor-application
spec:
  selector:
    matchLabels:
      app: kor-application
  template:
    metadata:
      labels:
        app: kor-application
    spec:
      containers:
      - name: kor-application
        image: 10.63.20.34:80/kor:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred