apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-report-app
  namespace: s3
  labels:
    app: bucket-report-app
spec:
  selector:
    matchLabels:
      app: bucket-report-app
  template:
    metadata:
      labels:
        app: bucket-report-app
    spec:
      containers:
      - name: bucket-report-app
        image: 10.63.20.34:80/bucket-report:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
