apiVersion: v1
kind: Service
metadata:
  name: aws-service
  namespace: aws
spec:
  type: NodePort
  selector:
    app: aws-application
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31730
      
      
 