apiVersion: v1
kind: Service
metadata:
  name: bucket-report-service
  namespace: s3
spec:
  type: NodePort
  selector:
    app: bucket-report-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31728
      
      
 
