apiVersion: v1
kind: Service
metadata:
  name: ar-metrics-service
  namespace: ar
spec:
  type: NodePort
  selector:
    app: ar-metrics
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30141