
username=srinivas
password=srinivas@123
jenkinsurl=http://10.63.20.41:8080/
jenkinstoken=11b728d9a3614989f152e78fbe947b4519

# Enable CORS for all endpoints
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.mvc.cors.allowed-headers=*
