spring.application.name=auto-remediation

spring.main.allow-bean-definition-overriding=true
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.63.20.37:32001/alerts_data
spring.datasource.username=admin
spring.datasource.password=Admin@123

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
